### ISSUE TITLE
Is there a min required version of IE to render the Captcha images?

### ISSUE THREAD

**Issue by udaykadaboina** [pludoni/simple-captcha#34]
I have a user unable to see the images in IE. So was wondering if there are any min reqments for the IE to show the images?

**Comment by zealot128** [comment]
I never heard about any specific problems. The base captcha does not depend on javascript or svg or stuff like this, so all versions (>6?) should be fine.

Using the Refresh Button functionality requires jquery-rails/ujs though, so then that version will be the minimum version.
