### ISSUE TITLE
Captcha-generation with ImageMagick > 6.9.6 fails

### ISSUE THREAD

**Issue by LinuCC** [pludoni/simple-captcha#52]
ArchLinux @ 2016-11-14

ImageMagick with versions starting from `6.9.6` fail because no font is given;
Take for example an example-command generated by simple-captcha2:
```
convert -fill darkblue -background white -size 100x28 -wave 1x88 -gravity Center -pointsize 22 -implode 0.2 label:BXVXN jpeg:- 2>&1
```

The output will be
```
convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1312.
convert: no images defined `jpeg:-' @ error/convert.c/ConvertImageCommand/3257.
```

Specifying a font with `-font MyFont` in the command makes it work again.

See also https://github.com/ImageMagick/ImageMagick/issues/300

**Comment by LinuCC** [comment]
It seems that for now the problem is restricted to Arch Linux boxes.
In that case try to upgrade to ImageMagick 7 which does not have the problem, for example through the AUR-package `infinality-full`.

**Comment by roylez** [comment]
I am hitting the same bug with alpine-3.4 docker image. Imagemagick version is 	6.9.5.9. 

``` 	convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1310 ```

**Comment by zealot128** [comment]
First, are you sure to have freetype installed in the docker image? The link also says, that v.7 works fine, too.
If the font is just required for imagemagick 6.9.x now, one could add another config option that set a font.

If any of you want to take it on, I think just adding another option in https://github.com/pludoni/simple-captcha/blob/master/lib/simple_captcha/image.rb#L74 and a corresponding config option https://github.com/pludoni/simple-captcha/blob/master/lib/simple_captcha.rb#L69 would be fine.

**Comment by denschub** [comment]
Heads up: ImageMagick 6.9.7 is now riding Debian testing. Since upstream does not really care about this issue, I submitted a PR to at least allow us manually setting a font if needed.

**Comment by zealot128** [comment]
thx @denschub for the PR. Pushed new Gem Version 0.4.3 with only that adjustment included.

**Comment by denschub** [comment]
Appreciated, thanks!
